// Copyright (c) 2025 Kodama Project. All rights reserved.
// Released under the GPL-3.0 license as described in the file LICENSE.
// Authors: Kokic (@kokic), Spore (@s-cerevisiae)

use camino::{Utf8Path, Utf8PathBuf};
use clap::Parser;
use eyre::Context;

use crate::{
    config::{self, wanshi},
    environment, path_utils,
    slug::Ext,
};

#[derive(Parser)]
pub struct NewCommandCli {
    #[command(subcommand)]
    pub command: NewCommand,
}

#[derive(clap::Subcommand)]
pub enum NewCommand {
    /// Create a new wanshi site.
    #[command(visible_alias = "s")]
    Site(NewSiteCommand),

    /// Create a new config file.
    #[command(visible_alias = "c")]
    Config(NewConfigCommand),

    /// Create a new post.
    #[command(visible_alias = "p")]
    Post(NewPostCommand),
}

#[derive(clap::Args)]
pub struct NewSiteCommand {
    /// Path to the new site.
    #[arg(required = true)]
    pub path: Utf8PathBuf,
}

pub fn new_site(command: &NewSiteCommand) -> eyre::Result<()> {
    let site_path = &command.path;
    if site_path.exists() {
        return Err(eyre::eyre!("Already exists: {}", site_path));
    }

    std::fs::create_dir_all(site_path).wrap_err("failed to create site directory")?;
    println!("Created new site at: {}", site_path);

    add_project_files(site_path)?;
    Ok(())
}

pub fn add_project_files(site_path: &Utf8Path) -> eyre::Result<()> {
    let default_config_path = site_path.join(config::DEFAULT_CONFIG_PATH);
    let default_source_dir = site_path.join(wanshi::DEFAULT_SOURCE_DIR);
    let default_assets_dir = site_path.join(wanshi::DEFAULT_ASSETS_DIR);
    let default_gitignore_path = site_path.join(".gitignore");

    // Create default config file in the new site directory
    new_config_inner(&default_config_path)?;

    // Create the default source directory `trees`
    std::fs::create_dir(&default_source_dir)
        .wrap_err("failed to create default source directory")?;

    // Create the default assets directory `assets`
    std::fs::create_dir(&default_assets_dir)
        .wrap_err("failed to create default assets directory")?;

    // Create the .gitignore
    std::fs::write(&default_gitignore_path, DEFAULT_GITIGNORE)
        .wrap_err("failed to create .gitignore")?;

    // Create the default index section in the new site directory
    new_section_inner(
        &Utf8PathBuf::from(DEFAULT_SECTION_PATH),
        DEFAULT_TEMPLATE,
        &default_config_path,
    )?;

    // Create the default Typst library directory `trees/_lib`
    let default_lib_dir = default_source_dir.join("_lib");
    std::fs::create_dir(&default_lib_dir).wrap_err("failed to create default _lib directory")?;
    std::fs::write(
        default_lib_dir.join("wanshi.typ"),
        include_str!("../include/wanshi.typ"),
    )?;

    Ok(())
}

#[derive(clap::Args)]
pub struct NewConfigCommand {
    /// Path to the new configuration file.
    #[arg(default_value_t = config::DEFAULT_CONFIG_PATH.into())]
    pub path: String,
}

pub fn new_config(command: &NewConfigCommand) -> eyre::Result<()> {
    new_config_inner(&Utf8PathBuf::from(&command.path))
}

pub fn new_config_inner(config_path: &Utf8PathBuf) -> Result<(), eyre::Error> {
    let config = config::Config::default();
    let toml = toml::to_string(&config).wrap_err("failed to serialize default config")?;

    std::fs::write(config_path, toml).wrap_err("failed to create default config file")?;
    println!("Created new config at: {}", config_path);
    Ok(())
}

pub const DEFAULT_SECTION_PATH: &str = "./index.typ";

pub const DEFAULT_TEMPLATE: &str = "./template";

/// The library import is root-absolute so the skeleton compiles at any depth in
/// the source tree; a tree-relative import only resolves for notes sitting at
/// the very top.
pub const DEFAULT_TEMPLATE_CONTENT_TYPST: &str = r#"
#import "/_lib/wanshi.typ": *

#show: wanshi

#metadata((
  "title": "<FILE_NAME>",
))
"#;
pub const DEFAULT_GITIGNORE: &str = r#"# Generated by wanshi
/.cache
.DS_Store
"#;

#[derive(clap::Args)]
pub struct NewPostCommand {
    /// Path to the new section.
    #[arg(required = true)]
    pub path: Utf8PathBuf,

    /// Path to the template file to use for the new section.
    #[arg(short, long, default_value_t = DEFAULT_TEMPLATE.to_string())]
    pub template: String,

    /// Path to the configuration file (e.g., "Wanshi.toml").
    #[arg(short, long, default_value_t = config::DEFAULT_CONFIG_PATH.into())]
    pub config: String,
}

/// This function invoked the [`config::init_environment`] function to initialize the environment]
pub fn new_section(command: &NewPostCommand) -> eyre::Result<()> {
    new_section_inner(
        &command.path,
        &command.template,
        Utf8Path::new(&command.config),
    )
}

/// This function invoked the [`config::init_environment`] function to initialize the environment]
fn new_section_inner(path: &Utf8Path, template: &str, config: &Utf8Path) -> eyre::Result<()> {
    environment::init_environment(config.to_owned(), environment::BuildMode::Publish)?;

    let section_relative_path = normalize_new_section_path(path)?;
    let section_relative_path = strip_new_post_tree_prefix(
        section_relative_path.as_path(),
        &environment::trees_dir_without_root(),
    );
    let default_not_exists = template == DEFAULT_TEMPLATE && !std::fs::exists(template)?;

    let content = if default_not_exists {
        DEFAULT_TEMPLATE_CONTENT_TYPST.to_string()
    } else {
        std::fs::read_to_string(template)
            .map_err(|e| eyre::eyre!("failed to read template file: {}", e))?
    };

    let filestem = section_relative_path.file_stem().ok_or_else(|| {
        eyre::eyre!(
            "invalid section path (missing file name): {}",
            section_relative_path
        )
    })?;
    let content = content.replace("<FILE_NAME>", filestem);

    let section_path = environment::trees_dir().join(&section_relative_path);

    if section_path.exists() {
        return Err(eyre::eyre!("already exists: {}", section_path));
    } else {
        let parent = section_path.parent().ok_or_else(|| {
            eyre::eyre!(
                "failed to resolve parent directory for section path: {}",
                section_path
            )
        })?;
        std::fs::create_dir_all(parent)
            .map_err(|e| eyre::eyre!("failed to create section directory: {}", e))?;
    }

    std::fs::write(&section_path, content)
        .map_err(|e| eyre::eyre!("failed to create section file: {}", e))?;
    println!("Created new section at: {}", section_path);

    Ok(())
}

fn normalize_new_section_path(path: &Utf8Path) -> eyre::Result<Utf8PathBuf> {
    match path.extension() {
        // Any recognized source extension is kept as written, so existing sites
        // using `.typst` can keep creating notes that match their convention.
        Some(ext) if ext.parse::<Ext>().is_ok() => Ok(path.to_owned()),
        Some(other) => Err(eyre::eyre!(
            "unsupported section extension `.{}`; expected `.{}` or `.{}`",
            other,
            Ext::Typ,
            Ext::Typst
        )),
        None => {
            let mut section_path = path.to_owned();
            section_path.set_extension(Ext::Typ.to_string());
            Ok(section_path)
        }
    }
}

fn strip_new_post_tree_prefix(path: &Utf8Path, trees_dir_without_root: &str) -> Utf8PathBuf {
    let normalized_path = Utf8PathBuf::from(path_utils::pretty_path(path));
    let normalized_trees_dir = Utf8PathBuf::from(path_utils::pretty_path(Utf8Path::new(
        trees_dir_without_root,
    )));

    if normalized_path.as_str().is_empty() || normalized_trees_dir.as_str().is_empty() {
        return normalized_path;
    }

    match normalized_path.strip_prefix(normalized_trees_dir.as_path()) {
        Ok(stripped) if !stripped.as_str().is_empty() => stripped.to_owned(),
        _ => normalized_path,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_normalize_new_section_path_appends_typ_when_missing_extension() {
        let path = normalize_new_section_path(Utf8Path::new("notes/foo"))
            .expect("should normalize path");

        assert_eq!(path, Utf8PathBuf::from("notes/foo.typ"));
    }

    #[test]
    fn test_normalize_new_section_path_respects_explicit_extension() {
        // Both source extensions are preserved as written, so a site that still
        // uses `.typst` keeps creating notes that match its own convention.
        for name in ["notes/foo.typ", "notes/foo.typst"] {
            let path = normalize_new_section_path(Utf8Path::new(name))
                .expect("should preserve an explicit source extension");
            assert_eq!(path, Utf8PathBuf::from(name));
        }
    }

    #[test]
    fn test_default_template_import_resolves_at_any_depth() {
        // A tree-relative import only resolves for notes at the top of the
        // source tree, so the scaffold must use the root-absolute form.
        assert!(DEFAULT_TEMPLATE_CONTENT_TYPST.contains(r#"#import "/_lib/wanshi.typ""#));
    }

    #[test]
    fn test_normalize_new_section_path_rejects_unsupported_extension() {
        let err = normalize_new_section_path(Utf8Path::new("notes/foo.md")).unwrap_err();
        assert!(format!("{err}").contains("unsupported section extension"));
    }

    #[test]
    fn test_strip_new_post_tree_prefix_strips_leading_tree_directory() {
        let stripped = strip_new_post_tree_prefix(Utf8Path::new("trees/notes/a.typst"), "trees");
        assert_eq!(stripped, Utf8PathBuf::from("notes/a.typst"));
    }

    #[test]
    fn test_strip_new_post_tree_prefix_handles_dot_prefix_path() {
        let stripped = strip_new_post_tree_prefix(Utf8Path::new("./trees/notes/a.typst"), "trees");
        assert_eq!(stripped, Utf8PathBuf::from("notes/a.typst"));
    }

    #[test]
    fn test_strip_new_post_tree_prefix_keeps_non_tree_prefixed_path() {
        let stripped = strip_new_post_tree_prefix(Utf8Path::new("notes/a.typst"), "trees");
        assert_eq!(stripped, Utf8PathBuf::from("notes/a.typst"));
    }

    #[test]
    fn test_strip_new_post_tree_prefix_supports_nested_tree_root() {
        let stripped = strip_new_post_tree_prefix(
            Utf8Path::new("content/trees/notes/a.typst"),
            "content/trees",
        );
        assert_eq!(stripped, Utf8PathBuf::from("notes/a.typst"));
    }
}
