// Copyright (c) 2025 Kodama Project. All rights reserved.
// Released under the GPL-3.0 license as described in the file LICENSE.
// Authors: Kokic (@kokic)

use eyre::WrapErr;

use crate::{config, environment};

#[derive(clap::Args)]
pub struct SnipCommand {
    /// Path to the configuration file (e.g., "Wanshi.toml").
    #[arg(short, long, default_value_t = config::DEFAULT_CONFIG_PATH.into())]
    config: String,

    /// Generate `.vscode/katex.code-snippets`.
    #[arg(short, long)]
    katex: bool,
}

/// This function invokes the [`environment::init_environment`] function to initialize the environment
pub fn snip(command: &SnipCommand) -> eyre::Result<()> {
    let config_path = &command.config;
    environment::init_environment(config_path.into(), environment::BuildMode::Serve)?;

    if command.katex {
        katex_snippets()?;
    }

    Ok(())
}

fn katex_snippets() -> eyre::Result<()> {
    let snippets_path = environment::root_dir()
        .join(".vscode")
        .join("katex.code-snippets");
    environment::create_parent_dirs(&snippets_path);

    // Generated by: https://github.com/kodama-community/vscode-katex-snippets
    let json = include_str!("../include/katex-snippets.json");
    std::fs::write(&snippets_path, json)
        .wrap_err_with(|| format!("failed to write snippets to `{}`", snippets_path))?;

    Ok(())
}
