// Copyright (c) 2025 Kodama Project. All rights reserved.
// Released under the GPL-3.0 license as described in the file LICENSE.
// Authors: Kokic (@kokic), Alias Qli (@AliasQli), Spore (@s-cerevisiae)

use std::collections::{HashMap, HashSet};

use eyre::{eyre, WrapErr};

use crate::{
    environment::{self, verify_and_file_hash},
    slug::{Ext, Slug},
};

use super::section::UnresolvedSection;
use super::{
    compile_from_shallows,
    incremental::{dirty_source_slugs, source_relative_path},
    parse_source_sections,
    stale::cleanup_stale_slug_artifacts,
    write_entry_cache, CompileOutputs, DirtySet, Workspace,
};

#[derive(Default)]
pub struct ServeCompileSession {
    initialized: bool,
    shallows: HashMap<Slug, UnresolvedSection>,
    source_sections: HashMap<Slug, Vec<Slug>>,
}

impl ServeCompileSession {
    pub fn is_initialized(&self) -> bool {
        self.initialized
    }

    pub fn compile_full(
        &mut self,
        workspace: Workspace,
        outputs: CompileOutputs,
    ) -> eyre::Result<()> {
        let stale_slugs = cleanup_stale_slug_artifacts(&workspace)
            .wrap_err("failed to clean stale slug artifacts")?;
        let (shallows, source_sections) = super::collect_shallows_with_sources(&workspace, None)?;
        self.shallows = shallows;
        self.source_sections = source_sections;
        self.initialized = true;
        compile_from_shallows(&workspace, &self.shallows, None, outputs, stale_slugs)
    }

    pub fn compile_incremental(
        &mut self,
        workspace: Workspace,
        dirty_paths: &DirtySet,
        outputs: CompileOutputs,
    ) -> eyre::Result<()> {
        let stale_slugs = cleanup_stale_slug_artifacts(&workspace)
            .wrap_err("failed to clean stale slug artifacts")?;

        let removed_sources: Vec<Slug> = self
            .source_sections
            .keys()
            .copied()
            .filter(|source_slug| !workspace.slug_exts.contains_key(source_slug))
            .collect();
        for source_slug in removed_sources {
            if let Some(slugs) = self.source_sections.remove(&source_slug) {
                for slug in slugs {
                    self.shallows.remove(&slug);
                }
            }
        }

        let dirty_slugs = dirty_source_slugs(&workspace, dirty_paths);
        let mut parse_targets: HashSet<Slug> = dirty_slugs.clone();

        for (&slug, &ext) in &workspace.slug_exts {
            if self.needs_refresh(slug, ext) {
                parse_targets.insert(slug);
            }
        }

        let needs_full_write = parse_targets.iter().any(|slug| !dirty_slugs.contains(slug));

        for slug in parse_targets {
            let Some(&ext) = workspace.slug_exts.get(&slug) else {
                continue;
            };
            let relative_path = source_relative_path(slug, ext);
            let _ = verify_and_file_hash(relative_path.as_path())
                .wrap_err_with(|| eyre!("failed to verify hash of `{relative_path}`"))?;
            let entry_path = environment::entry_file_path(relative_path.as_path());
            let sections = parse_source_sections(slug, ext)?;
            write_entry_cache(entry_path.as_path(), &sections)?;

            if let Some(previous_slugs) = self.source_sections.remove(&slug) {
                for previous_slug in previous_slugs {
                    self.shallows.remove(&previous_slug);
                }
            }

            let produced_slugs: Vec<Slug> = sections
                .iter()
                .map(|(section_slug, _)| *section_slug)
                .collect();
            for (section_slug, section) in sections {
                if let Some(owner) = self.slug_owner(section_slug) {
                    if owner != slug {
                        return Err(eyre!(
                            "section slug collision: `{}` is generated by both `{}` and `{}`",
                            section_slug,
                            owner,
                            slug
                        ));
                    }
                }
                self.shallows.insert(section_slug, section);
            }
            self.source_sections.insert(slug, produced_slugs);
        }
        self.initialized = true;

        compile_from_shallows(
            &workspace,
            &self.shallows,
            if needs_full_write {
                None
            } else {
                Some(dirty_paths)
            },
            outputs,
            stale_slugs,
        )
    }

    pub fn rewrite_all_from_memory(&mut self, outputs: CompileOutputs) -> eyre::Result<()> {
        // Global/template/theme changes can require re-emitting all pages,
        // but they don't require reparsing source trees.
        let workspace = Workspace {
            slug_exts: HashMap::new(),
        };
        compile_from_shallows(&workspace, &self.shallows, None, outputs, HashSet::new())
    }

    fn needs_refresh(&self, slug: Slug, ext: Ext) -> bool {
        if !self.source_sections.contains_key(&slug) {
            return true;
        }
        let Some(shallow) = self.shallows.get(&slug) else {
            return true;
        };
        let expected_ext = ext.to_string();
        shallow
            .ext()
            .map(|value| value != expected_ext.as_str())
            .unwrap_or(true)
    }

    fn slug_owner(&self, slug: Slug) -> Option<Slug> {
        self.source_sections
            .iter()
            .find_map(|(source_slug, slugs)| slugs.contains(&slug).then_some(*source_slug))
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        compiler::section::{HTMLContent, UnresolvedSection},
        entry::{HTMLMetaData, KEY_EXT, KEY_SLUG},
        ordered_map::OrderedMap,
    };

    use super::*;

    fn shallow(slug: &str, ext: &str) -> UnresolvedSection {
        let mut metadata = OrderedMap::new();
        metadata.insert(KEY_SLUG.to_string(), HTMLContent::Plain(slug.to_string()));
        metadata.insert(KEY_EXT.to_string(), HTMLContent::Plain(ext.to_string()));
        UnresolvedSection {
            metadata: HTMLMetaData(metadata),
            content: HTMLContent::Plain(String::new()),
        }
    }

    #[test]
    fn test_needs_refresh_when_shallow_missing() {
        let session = ServeCompileSession::default();
        assert!(session.needs_refresh(Slug::new("a"), Ext::Typst));
    }

    #[test]
    fn test_needs_refresh_when_extension_matches() {
        let mut session = ServeCompileSession::default();
        session
            .source_sections
            .insert(Slug::new("a"), vec![Slug::new("a")]);
        session
            .shallows
            .insert(Slug::new("a"), shallow("a", "typst"));
        assert!(!session.needs_refresh(Slug::new("a"), Ext::Typst));
    }

    #[test]
    fn test_needs_refresh_when_extension_differs() {
        let mut session = ServeCompileSession::default();
        session
            .source_sections
            .insert(Slug::new("a"), vec![Slug::new("a")]);
        session
            .shallows
            .insert(Slug::new("a"), shallow("a", "stale"));
        assert!(session.needs_refresh(Slug::new("a"), Ext::Typst));
    }

    #[test]
    fn test_rewrite_all_from_memory_without_shallows_is_noop() {
        // Runs inside a test environment because rewriting reconciles the
        // output directory, so it must not touch the real working tree.
        let root = crate::test_io::case_dir("serve-session-rewrite");
        std::fs::create_dir_all(root.as_std_path()).unwrap();
        crate::environment::with_test_environment(
            root.clone(),
            crate::environment::BuildMode::Serve,
            || {
                let mut session = ServeCompileSession {
                    initialized: true,
                    ..ServeCompileSession::default()
                };
                session
                    .rewrite_all_from_memory(CompileOutputs {
                        indexes: false,
                        graph: false,
                    })
                    .unwrap();
            },
        );
        let _ = std::fs::remove_dir_all(root.as_std_path());
    }
}
