#import "/_lib/wanshi.typ": *
#import "/_showcase.typ": showcase

#show: showcase

#metadata((
  "title": "References",
  "date": "2026-08-14",
  // An index whose job is to link everything would otherwise put a backlink to
  // itself on every note it lists. This keeps the listings clean.
  "asback": "false",
))

Notes here carry a `reference` taxon, so linking to one cites it: the link drops
into the citing page's footer instead of interrupting the sentence. See
#local("/guide/links") for the mechanism.

Two of these were written by hand. #local("/refs/knuth1984literate") was not —
it was generated by `wanshi refs sync` from `trees/_bib/refs.bib`, which is
where a reference manager would write. Compare the two: the generated one
carries the citation key, DOI and container as metadata, so a paper can collect
it back out with `wanshi refs export`.

#by-taxon("reference", title: none)
