#import "/_lib/wanshi.typ": *

#show: wanshi

// Generated by `wanshi refs sync`. Edits are overwritten — notes about
// this work belong in an ordinary note that links here. Delete this
// comment to take the file over by hand.
#metadata((
  "title": "Knuth 1984 — Literate Programming",
  "taxon": "reference",
  "date": "1984",
  "author": "Donald E. Knuth",
  "citekey": "knuth1984literate",
  "type": "article",
  "container": "The Computer Journal",
  "doi": "10.1093/comjnl/27.2.97",
  "parent": "refs/index",
))

_The Computer Journal_ *27*(2), 97–111.

#external("https://doi.org/10.1093/comjnl/27.2.97", "doi:10.1093/comjnl/27.2.97")
